use roman::convert::{to,from};
use test_case::test_case;

// #[test]
// fn a_sample_test() {
//     assert_eq!(1,1);
// }

#[test_case(1 => "I")]
#[test_case(2 => "II")]
#[test_case(3 => "III")]
#[test_case(4 => "IV")]
#[test_case(5 => "V")]
#[test_case(6 => "VI")]
#[test_case(7 => "VII")]
#[test_case(8 => "VIII")]
#[test_case(9 => "IX")]
#[test_case(10 => "X")]
#[test_case(11 => "XI")]
#[test_case(14 => "XIV")]
#[test_case(15 => "XV")]
#[test_case(16 => "XVI")]
#[test_case(19 => "XIX")]
#[test_case(20 => "XX")]
#[test_case(21 => "XXI")]
#[test_case(39 => "XXXIX")]
#[test_case(40 => "XL")]
#[test_case(41 => "XLI")]
#[test_case(42 => "XLII")]
#[test_case(43 => "XLIII")]
#[test_case(44 => "XLIV")]
#[test_case(45 => "XLV")]
#[test_case(46 => "XLVI")]
#[test_case(47 => "XLVII")]
#[test_case(48 => "XLVIII")]
#[test_case(49 => "XLIX")]
#[test_case(50 => "L")]
#[test_case(89 => "LXXXIX")]
#[test_case(90 => "XC")]
#[test_case(91 => "XCI")]
#[test_case(99 => "XCIX")]
#[test_case(100 => "C")]
#[test_case(101 => "CI")]
#[test_case(200 => "CC")]
#[test_case(399 => "CCCXCIX")]
#[test_case(400 => "CD")]
#[test_case(401 => "CDI")]
#[test_case(499 => "CDXCIX")]
#[test_case(500 => "D")]
#[test_case(501 => "DI")]
#[test_case(899 => "DCCCXCIX")]
#[test_case(900 => "CM")]
#[test_case(999 => "CMXCIX")]
#[test_case(1000 => "M")]
#[test_case(1001 => "MI")]
#[test_case(1968 => "MCMLXVIII")]
fn test_to(arabic: u16) -> String {
    to(arabic)
}

#[test_case("I" => 1)]
#[test_case("II" => 2)]
#[test_case("III" => 3)]
#[test_case("IV" => 4)]
#[test_case("V" => 5)]
#[test_case("VI" => 6)]
#[test_case("VII" => 7)]
#[test_case("VIII" => 8)]
#[test_case("IX" => 9)]
#[test_case("X" => 10)]
#[test_case("XI" => 11)]
#[test_case("XIV" => 14)]
#[test_case("XV" => 15)]
#[test_case("XVI" => 16)]
#[test_case("XIX" => 19)]
#[test_case("XX" => 20)]
#[test_case("XXI" => 21)]
#[test_case("XXXIX" => 39)]
#[test_case("XL" => 40)]
#[test_case("XLI" => 41)]
#[test_case("XLII" => 42)]
#[test_case("XLIII" => 43)]
#[test_case("XLIV" => 44)]
#[test_case("XLV" => 45)]
#[test_case("XLVI" => 46)]
#[test_case("XLVII" => 47)]
#[test_case("XLVIII" => 48)]
#[test_case("XLIX" => 49)]
#[test_case("L" => 50)]
#[test_case("LXXXIX" => 89)]
#[test_case("XC" => 90)]
#[test_case("XCI" => 91)]
#[test_case("XCIX" => 99)]
#[test_case("C" => 100)]
#[test_case("CI" => 101)]
#[test_case("CC" => 200)]
#[test_case("CCCXCIX" => 399)]
#[test_case("CD" => 400)]
#[test_case("CDI" => 401)]
#[test_case("CDXCIX" => 499)]
#[test_case("D" => 500)]
#[test_case("DI" => 501)]
#[test_case("DCCCXCIX" => 899)]
#[test_case("CM" => 900)]
#[test_case("CMXCIX" => 999)]
#[test_case("M" => 1000)]
#[test_case("MI" => 1001)]
#[test_case("MCMLXVIII" => 1968)]
fn test_from(roman: &str) -> u16 {
    from(roman)
}
